name       : mailimporter
version    : 20.04.1
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/mailimporter-20.04.1.tar.xz : 4654e9e0c211f6eeb71e1e43e4d05b514a0890990a622bb707f137a801bf49a4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
