name       : mailimporter
version    : 21.12.3
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/mailimporter-21.12.3.tar.xz : 53dbab7697658d38dbbf6e7f31fbe97a88fcad1ca3a77cb540ce04d7fe4f9951
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
