name       : mailimporter
version    : 19.08.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/mailimporter-19.08.0.tar.xz : 242f1a93b3521abc68ca8e1abfc75acd0b59e1e2d553df80a057645102246dd7
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
