name       : mailimporter
version    : 18.08.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/mailimporter-18.08.3.tar.xz : f56af822321abdb07b2f766d3085e9dc8e26e06875d6e9f45f60b18f4fda23ab
license    : GPL-2.0-only
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
