name       : mailimporter
version    : 18.12.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/mailimporter-18.12.1.tar.xz : 282904963ac283cbf8b2d67251fe5d61969051f99b328ef5664e6db694c40fcd
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
