name       : mailimporter
version    : 23.04.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/mailimporter-23.04.2.tar.xz : b3e599e726b3cfe32f2d3ee41d9b024b38002c0767d9ced312d0fff6dface775
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
