name       : mailimporter
version    : 21.08.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/mailimporter-21.08.0.tar.xz : 3f1fdc85903cde153b49dcf6251bca35ee128d2b8a591c129b033b380a9d2a8d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
