name       : mailimporter
version    : 19.08.2
release    : 25
source     :
    - https://download.kde.org/stable/applications/19.08.2/src/mailimporter-19.08.2.tar.xz : 27780c381919ebc9e6fc0de7021cd03277dd3962d4c4c15770fcf44cd6126814
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
