name       : mailimporter
version    : 18.08.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/mailimporter-18.08.0.tar.xz : 7a75775f69ab4c21f0a3c00fd7a5dff8112d4984e2f103707272568150fbdc3f
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
