name       : mailimporter
version    : 21.08.2
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/mailimporter-21.08.2.tar.xz : 87d38324b6af3d001006703f912a5ad74ff0a83bed79d109e421f3afe15ba06d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
