name       : mailimporter
version    : 22.12.1
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/mailimporter-22.12.1.tar.xz : b66490420506f0d73ea59b5fbc3954e1f96ea424ac5a5f03026228aab7eaf7b1
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - kpimtextedit-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
