name       : mailimporter
version    : 20.08.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/mailimporter-20.08.2.tar.xz : a255b60378c1cf77e517919d072cb44bd8c25e8ed8f07429763bb7915b3cc711
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
