name       : mailimporter
version    : 19.12.1
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/mailimporter-19.12.1.tar.xz : c1a042560438d6f6195a1f64355515489b74a44c1d2f5f547ced6785439215f1
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - karchive-devel
    - kcompletion-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemmodels-devel
    - kmime-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
