name       : mailimporter
version    : 21.08.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/mailimporter-21.08.1.tar.xz : cea27f3fd0095884d937cd7e4b094f983746497abaac2f7c2e816adbd68f7116
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
