name       : mailimporter
version    : 20.12.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/mailimporter-20.12.3.tar.xz : d67af2f3f62ccf934b4c23982750c05e70bbc144bea231eba560278363de73d2
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
