name       : mailimporter
version    : 20.12.2
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/mailimporter-20.12.2.tar.xz : db2314d02327bdc9b3e083d08a0549145c4deb82aeeeef4e4c30f2b7bdcb5499
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Mail importer library
description: |
    Mail importer library.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - karchive-devel
    - kcontacts-devel
    - kimap-devel
    - kio-devel
    - pimcommon-devel
rundeps    :
    - devel :
        - karchive-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
